function UT_loading(strate,ts,incs,freq)
F11 = strate;
% update F11 for its size
if size(F11,2) ~= size(ts,2)
    F11 = F11 * ones(size(ts));
end
% prepare the loading states
    ut_load(1,1) = cellstr([...
        'Fdot ' num2str(F11(1)) ' 0 0 0 * 0 0 0 * ' ...
        'stress * * * * 0 * * * 0 time ' ...
        num2str(ts(1)) ...
        ' incs ' num2str(incs(1)) ...
        ' freq ' num2str(freq(1))]);
for i = 2:size(ts,2)
    ut_load(end+1,1) = cellstr([...
        'Fdot ' num2str(F11(i)) ' 0 0 0 * 0 0 0 * ' ...
        'stress * * * * 0 * * * 0 time ' ...
        num2str(ts(i)) ...
        ' incs ' num2str(incs(i)) ...
        ' freq ' num2str(freq(i)) ' dropguessing']);
end

% Export the UT.load file
fid = fopen('UT.load','w');
for i = 1:size(ut_load,1)
    fprintf(fid,'%s\n',ut_load{i});
end
fclose(fid);
end